export const ERROR_MESSAGES = {
    INTERNAL_ERROR: "Internal server error",
    UNAUTHENTICATED: "Unauthenticated",
    UNAUTHORIZED: "Unauthorized",
    NOT_FOUND: "Not found",
    INVALID_CREDENTIAL: "Username or password is not correct",
    INVALID_REQUEST: "Invalid request",
    EMAIL_INVALID_CREDENTIAL: "Email is not correct",
    PASSWORD_INVALID_CREDENTIAL: "Password is not correct",
    EMAIL_ALREADY_TAKEN: "This email is already taken",
    EMAIL_NOT_FOUND: "This email is not found",
    DEVICE_NOT_FOUND: "This device is not found",
    USER_ALREADY_EXIST: "This user already exists",
    USER_NOT_EXIST: "This user not exists",
    DEVICE_ALREADY_EXIST: "This device already exists",
    ACCOUNT_NOT_VERIFY: "Your account has not yet been verified",
    INVALID_TOKEN: "This token is not valid",
    GROUP_NAME_ALREADY_TAKEN: "This group name is already taken",
    TEAM_NAME_ALREADY_TAKEN: "This team name is already taken",
    POSITION_LONG_NAME_ALREADY_TAKEN:
      "The position with this long name is already taken",
    POSITION_SHORT_NAME_ALREADY_TAKEN:
      "The position with this short name is already taken",
    FORBIDDEN_ERROR: "You don't currently have permission to access this page",
    STATUS_NOT_EDIT: "Only status PENDING is allowed edit",
    EMPLOYEE_TYPE_NOT_HAVE_POSITION: "Intern is not have position",
    BOD_NOT_HAVE_MANAGE: "Board of Directors is not have manage",
    INVALID_TEAM_ID: "OrganizationId is not team",
    INVALID_GROUP_ID: "OrganizationId is not group",
    CODE_EXIST: "Code already exists",
    INVALID_PHONE_NUMBER: "Must be a valid phone number",
    INVALID_ALPHABET_CHARACTER: "Only accept alphabet",
    PROJECT_EXIST: "This project already exists",
    PROJECT_NOT_EXIST: "This project doesn't already exists",
    CATEGORY_NOT_EXIST: "This category doesn't already exists",
    TRACKKING_NOT_EXIST: "This tracking doesn't already exists",
    MEMBER_NOT_EXIT: "Member doesn't already exists",
    PROJECT_MANAGEMENT_NOT_EXIT: "This project management doesn't already exists",
    INVALID_NUMBER: "Only accept number",
    INVALID_FIRST_NAME: "First name is required",
    INVALID_LAST_NAME: "Last name is required",
    INVALID_MIDDLE_NAME: "Middle name is required",
    NATIONALITY_REQUIRED : "Nationality is required",
    MUST_BE_DATE: "This field must be date",
    DATE_OF_JOIN_REQUIRED: "Date of joining is required",
    EMPLOYEE_TYPE_REQUIRED: "Employee type is required",
    EMPLOYEE_CODE_REQUIRED: "Employee code is required",
    EMAIL_REQUIRED: "Email is required",
    INVALID_EMAIL: "Must be a valid email",
    POSITION_REQUIRED: "Position is required",
    SPECIAL_CHAR_NOT_ALLOW: "Special character is not allow",
    NUMBER_NOT_ALLOW: "Number is not allow",
    FIELD_NOT_EMPTY: "Please fill value!!!",
    NAME_REQUIRED: "Name is required",
    CONTACT_NOT_EXSIST: "Contact not exists",
    VALUE_OF_ADJUSTMENT: "Value of Adjustment is required",
    RANGE_VALUE_OF_ADJUSTMENT: "Value of Adjustment must be between 1 and 5.",
    ROLE_NOT_EXISTS: "Role not exists",
    PROJECTS_CREATED_FEEDBACK: "This Project created feedback!!!",
    ALL_FIELDS_REQUIRED: "All fields are required",
    COMMENT_NOT_EXIST: "Comment is not exist",
    LEAVETYPE_NOT_EXIST: "This leaveType doesn't already exists",
    NOTIFICATION_NOT_EXIST: "This notification doesn't already exists",
    TIMELINE_NOT_EXIST: "This timeline doesn't already exists",
    POSITION_NOT_EXIST: "This position doesn't already exists",
    WIKI_NOT_EXIST: "This wiki doesn't already exists",
    REACTION_NOT_EXIST: "This reaction doesn't already exists",
    UNIQUE_CONSTRAINT_FAILED: "Unique constraint failed on the fields: (`userId`,`wikiId`)",
    REQUEST_IS_NOT_EXSIST: "Request is not exsist",
    PASSWORD: "Must be at least 8 characters, least 1 number, least 1 in Capital Case !",
    MIN_PASSWORD: "At least 8 character",
    MAX_PASSWORD: "Maximum 16 character",
  };
  
  export const STATUS_CODE = {
    BAD_REQUEST: 400,
    NOT_FOUND: 404,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    OK: 200,
    CREATED: 201,
    INTERNAL_SERVER_ERROR: 500,
  };
  