import Head from 'next/head';
import Layout from '@components/common/Layout';

export default function Home() {
  return (
    <>
      <Head>
        <title>Project NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <div>Body</div>
        </Layout>
      </main>
    </>
  )
}
