import { useEffect, useState } from 'react';
import { getData } from '@services/api-clients/getComment';
import Head from 'next/head';
import Layout from '@components/common/Layout';
import Tab from '@components/common/TabCommon';
import Comment from '@components/CommentComponent';
import Todo from '@components/TodosComponent';

export default function SignupSuccess() {
  const [data, setData] = useState<any>([]);
    
    const fetchData =  async () => {
        const dataAPI = await getData('comments');
        setData(dataAPI.data);
    }

    useEffect(() => {
        fetchData();
    }, [])

    const items = [
      {
        key: '1',
        label: `Comments`,
        children: <Comment data={data} />,
      },
      {
        key: '2',
        label: `Todos`,
        children: <Todo/>,
      },
    ];

  return (
    <>
      <Head>
        <title>Sign Up Success</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <div>
            <Tab items={items} defaultActiveKey="1"/>
          </div>
        </Layout>
      </main>
    </>
  )
}
