import Head from 'next/head';
import Layout from '@components/common/Layout';
import { useEffect } from 'react';
import { getData } from '@services/api-clients/getComment';

export default function SignupSuccess() {
    const fetchData =  async () => {
        const data = await getData('comments');
        console.log(data);
    }

    useEffect(() => {
        console.log("start");
        fetchData();
    }, [])
    
  return (
    <>
      <Head>
        <title>Sign Up Success</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <div>

          </div>
        </Layout>
      </main>
    </>
  )
}
